## 7a. C sequest. in trees (3PG)

#' C_sequest_in_trees
#' @param core.dat UI data
#' @param forestry.dat UI forestry data
#' @return 3PG output
#' @export
C_sequest_in_trees <- function(core.dat,
                               forestry.dat) {

  # THIS FUNCTION...

  # Get 3PG templates
  parms_3PG <- read_excel("Templates/3PG_parms.xlsx",
                          sheet = "3PG_parms",
                          range = "A1:E24")

  species <- c("Scots_Pine", "Sitka_Spruce")

  parms_3PG <- as.data.frame(parms_3PG %>%
    filter(complete.cases(.)) %>%
    select(Var_name, all_of(species)))


  f_E_tab <-  read_excel("Templates/3PG_parms.xlsx",
                         sheet = "f_E",
                         range = "A1:E7")

  f_E_tab <- f_E_tab %>%
    select(Soil_type, Acc_temp, f_E)

  # Get full parameter lists for each area
  parms_3PG_by_area <- array(0,
                             dim = c(nrow(parms_3PG), # f_E and t_seedling_replant not included in template
                                     3, # Exp, Min, Max if defined
                                     length(grep("Area", names(forestry.dat)))), # number of areas considered
                             dimnames = list(c(parms_3PG$Var_name),
                                             c("Exp", "Min", "Max"),
                                             grep("Area", names(forestry.dat), value=T)))

  ii <- 1
  for (i in grep("Area", names(forestry.dat))) {

    # Species parameters (no range given)
    parms_3PG_by_area[parms_3PG$Var_name,,ii] <- parms_3PG[,which(colnames(parms_3PG) == species[forestry.dat[[i]]$species[1]])]

    # Accumulated temperature category based on wind farm site average temperature (not forest area)
    # May have non-zero range though unlikely due to current coarseness of environmental metric
    parms_3PG_by_area["acc_temp",,ii] <- sapply((core.dat$Peatland$T_air - 5) * 365, FUN = function(x) {
      if (x < 1050) {
        return(1)
      } else if (x < 1050) {
        return(2)
      } else {
        return(3)
      }
    })

    f_E_area <- f_E_tab[f_E_tab$Soil_type == forestry.dat[[i]]$soil_type[1],]
    parms_3PG_by_area["f_E",,ii] <- f_E_area$f_E[c(which(f_E_area$Acc_temp == parms_3PG_by_area["acc_temp",1,ii]),
                                                    which(f_E_area$Acc_temp == parms_3PG_by_area["acc_temp",2,ii]),
                                                    which(f_E_area$Acc_temp == parms_3PG_by_area["acc_temp",3,ii]))] # this allows re-indexing of same or different values in case of differences in Exp, Min and Max acc_temp

    # Forestry parameters
    parms_3PG_by_area["t_harv",,ii] <- forestry.dat[[i]]$t_harv
    parms_3PG_by_area["t_wf",,ii] <- core.dat$Windfarm$t_wf
    parms_3PG_by_area["t_replant",,ii] <- forestry.dat[[i]]$t_replant
    parms_3PG_by_area["t_seedling_replant",,ii] <- forestry.dat[[i]]$t_seedling_replant
    parms_3PG_by_area["t_replant_guar",,ii] <- core.dat$Windfarm$t_wf - forestry.dat[[i]]$t_replant
    parms_3PG_by_area["t_replant_guar", parms_3PG_by_area["t_replant_guar",,ii] < 0, ii] <- 0 # set to zero if negative

    ii <- ii + 1
  }

  # 3PG is run using a nested, vectorised approach for efficiency
  # Nesting applies run_3PG to a) Each area, b) Each of Exp, Min, Max

  ## Model pre-wind farm forestry
  out <- apply(parms_3PG_by_area, # remove t_seedling_replant (use default value of 0 for modelling pre-wf forestry)
               MAR = 3,
               FUN = function(y) {
                 apply(y,
                       MAR=2,
                       function(x) do.call(run_3PG, as.list(c(x, c(replant=0)))))
               })

  # SHOULD THIS BE HANDLED BY SIMPLY SUBSETTING THE ABOVE INSTEAD OF RE-RUNNING?
  ## Model replanted forestry
  out_replant <- apply(parms_3PG_by_area, # remove t_seedling_replant (use default value of 0 for modelling pre-wf forestry)
                   MAR = 3,
                   FUN = function(y) {
                     apply(y,
                           MAR=2,
                           function(x) do.call(run_3PG, as.list(c(x, c(replant=1)))))
                   })

  # Min and Max are not trivially defined by input values
  # Harvesting forest young (Min) means a substantial loss of sequestration potential due to the age modifier
  # Returned values for Min and Max are generated by selected min/max from the two runs, scanning the parameter space would be more representative
  getExpMinMax <- function(x) {
    if (x[3] < x[2]) {
      x0 <- x[3]
      x[3] <- x[2]
      x[2] <- x0
    }
    names(x) <- c("Exp", "Min", "Max")
    return(x)
  }

  seq_pot <- lapply(list_op(l1 = map(map(out, .f = "Exp"), .f = "NPP_01"),
                              l2 = map(map(out, .f = "Min"), .f = "NPP_01"),
                              l3 = map(map(out, .f = "Max"), .f = "NPP_01"),
                              func = "c"),
                      FUN = getExpMinMax)

  C_tot <- lapply(list_op(l1 = map(map(out, .f = "Exp"), .f = "NPP_0"),
                        l2 = map(map(out, .f = "Min"), .f = "NPP_0"),
                        l3 = map(map(out, .f = "Max"), .f = "NPP_0"),
                        func = "c"),
                FUN = getExpMinMax)

  seq_pot_replant <- lapply(list_op(l1 = map(map(out_replant, .f = "Exp"), .f = "NPP_01"),
                                l2 = map(map(out_replant, .f = "Min"), .f = "NPP_01"),
                                l3 = map(map(out_replant, .f = "Max"), .f = "NPP_01"),
                                func = "c"),
                        FUN = getExpMinMax)

  return(list(seq_pot = seq_pot,
              C_tot = C_tot,
              seq_pot_replant = seq_pot_replant))
}

run_3PG <- function(t_rotation = 50, # rotation length
                    rotation = 3, # no. rotations
                    t_step = 1, # time step
                    L_long = 4, # leaf longevity
                    pF = 0.25, # proportion carbon allocated to foliage
                    N0 = 0, # coefficient for allocation response to nitrogen (NOT USED)
                    R_long = 0, # fine root longevity (NOT USED)
                    Wl_init = 0.01, # initial foliage biomass # was 0.005; set to 0.01 after age at which leaf longevity impacts dynamics set to zero for simplicity
                    t_seedling_replant = 0, # seedling age at planting
                    SLA = 6, # specific leaf area
                    phi_p = 2880, # average annual photosynthetically active radiation
                    kP = 0.5, # extinction coefficient
                    acc_temp = 1, # accumulated temperature (not used)
                    f_E = 0.3176845825, # environmental modifier
                    A0.5 = 100, # age at 50% reduction in NPP
                    LAI_u = 3, # LAI understory
                    e_max = 0.00152, # maximum light use efficiency
                    YPP = 0.47, # NPP:GPP ratio
                    t_harv = 25, # age of forestry when felled for wind farm
                    t_wf = 25, # lifetime of wind farm
                    t_replant = 0, # years after felling when replanting occurs
                    t_replant_guar = 20, # years for which replanted forestry will be grown on the site
                    t1 = 25, # either t_wf or t_replant_guar
                    replant = 0, # boolean to select pre-wind farm or replanted forest for output
                    thin = data.frame(t = c(20, 25, 30, 35, 40, 45), # thinning regime (years/proportion harvested)
                                      p = c(0.189655172413793, 0.180555555555556, 0.166666666666667, 0.141538461538462, 0.050561797752809, 0.0537897310513447))) {

  if (replant == 0) {
    t_seedling_replant <- 0
  }

  t <- seq(0,t_rotation,by=t_step)
  res <- data.frame(matrix(0, nrow=length(t), ncol=10))
  colnames(res) <- c("t",
                     "thin",
                     "Wl",
                     "LAI",
                     "phi_pau",
                     "phi_pa_u",
                     "phi_pau_u",
                     "NPP",
                     "NPP_tot",
                     "NPP_cum")

  res$t <- t

  leaf_long_onset <- 0 # as in spreadsheet: suggest setting to zero!

  # Initialise 3PG
  res$Wl[1] <- Wl_init
  res$LAI[1] <- res$Wl[1] * SLA

  # SPREADSHEET ERROR
  # res$phi_pau[1] <- phi_p * f_E * (1 - exp(-kP * res$LAI[1])) * (1 / (1 + (res$t[1] / A0.5)^4)) # SPREADSHEET ERROR
  res$phi_pau[1] <- phi_p * f_E * (1 - exp(-kP * res$LAI[1])) * (1 / (1 + ((res$t[1] + t_seedling_replant) / A0.5)^4))

  res$phi_pa_u[1] <- phi_p * (1 - (1 - exp(-kP * res$LAI[1]))) * (1 - exp(-kP * LAI_u))
  res$phi_pau_u[1] <- res$phi_pa_u[1] * f_E
  res$NPP[1] <- YPP * e_max * res$phi_pau[1]
  res$NPP_tot[1] <- YPP * e_max * (res$phi_pau[1] +  res$phi_pau_u[1]) * 10 # convert from m-2 to ha-1
  res$NPP_cum[1] <- res$NPP_tot[1]

  # Iterate 3PG
  for (i in 2:nrow(res)) {
    if (!is.null(thin)) {
      # Add thinning (accounting for possible non-integer time step)
      if (nrow(thin) > 0 & res$t[i] >= thin$t[1]) {
        res$thin[i] <- thin$p[1]
        thin <- thin[-1,]
      }
    }

    # SPREADSHEET ERROR
    # if (res$t[i] < (t_seedling_replant + leaf_long_onset)) { # Leaf longevity not yet relevant SPREADSHEET ERROR
    if ((res$t[i] + t_seedling_replant) < leaf_long_onset) { # Leaf longevity not yet relevant
      res$Wl[i] <- res$Wl[i-1] * (1 - res$thin[i]) + t_step * res$NPP[i-1] * pF
    } else { # Accounting for leaf longevity
      res$Wl[i] <- res$Wl[i-1] * (1 - res$thin[i]) + t_step * (res$NPP[i-1] * pF - res$Wl[i-1] / L_long)
    }
    res$LAI[i] <- res$Wl[i] * SLA

    # SPREADSHEET ERROR
    # res$phi_pau[i] <- phi_p * f_E * (1 - exp(-kP * res$LAI[i])) * (1 / (1 + (res$t[i] / A0.5)^4)) # SPREADSHEET ERROR
    res$phi_pau[i] <- phi_p * f_E * (1 - exp(-kP * res$LAI[i])) * (1 / (1 + ((res$t[i] + t_seedling_replant) / A0.5)^4))

    res$phi_pa_u[i] <- phi_p * (1 - (1 - exp(-kP * res$LAI[i]))) * (1 - exp(-kP * LAI_u))
    res$phi_pau_u[i] <- res$phi_pa_u[i] * f_E
    res$NPP[i] <- YPP * e_max * res$phi_pau[i]
    res$NPP_tot[i] <- YPP * e_max * (res$phi_pau[i] +  res$phi_pau_u[i]) * 10 # convert from m-2 to ha-1
    res$NPP_cum[i] <- res$NPP_cum[i-1] + res$NPP_tot[i]
  }

  if (replant == 0) {
    t0 <- t_harv
    t1 <- t0 + t_wf
  } else {
    t0 <- t_seedling_replant
    t1 <- t0 + t_replant_guar
  }

  if (t_rotation < t1) {
    rotation <- floor(t1 / t_rotation) + 1
    res <- rbind(res, do.call(rbind, replicate(rotation-1, res[-nrow(res),], simplify=F)))
    res$t <- seq(0,(nrow(res)-1)*t_step,by=t_step)
  }

  NPP_0 <- res %>%
    filter(abs(t - t0) == min(abs(t - t0))) %>% # this in case of non-integer t/t0
    slice(1) %>%
    select(NPP_cum) %>%
    unname()

  NPP_01 <- res %>%
    filter(t >= t0 & t < t1) %>%
    select(NPP_tot) %>%
    sum()

  return(list(res = res,
              NPP_0 = NPP_0,
              NPP_01 = NPP_01))
}

if (0) { # testing reason for differences due to t_seedling_replant

  t_rotation <- 150

  out0 <- run_3PG(t_rotation = t_rotation, t_seedling_replant = 0, thin = NULL)
  out0b <- run_3PG(t_rotation = t_rotation, t_seedling_replant = 0, thin = NULL)
  out0c <- run_3PG(t_rotation = t_rotation, t_seedling_replant = 0, thin = NULL, Wl_init = 0.01)

  out1 <- run_3PG(t_rotation = t_rotation, t_seedling_replant = 10, thin = NULL, replant = 1)
  out2 <- run_3PG(t_rotation = t_rotation, t_seedling_replant = 10, thin = NULL, replant = 1)
  out3 <- run_3PG(t_rotation = t_rotation, t_seedling_replant = 10, thin = NULL, replant = 1, A0.5 = )

  # When seedlings planted at age 10, dynamics are different relative to planting at age 0 then subsetting the time series
  # Specifically, Wl is lower (unless and until Wl converges)
  # Also there are differences in the decay phase (once the age modifier kills off growth)

  plot(out0$res$t, out0$res$NPP, type='n', ylim=c(0,0.6))
  lines(out1$res$t, out1$res$NPP, type='l', col="red")
  lines(out2$res$t, out2$res$NPP, type='l', col="blue")
  lines(out0$res$t, out0$res$NPP, type='l', col="black")

  plot(out0$res$t, out0$res$NPP, type='n', ylim=c(0,0.6))
  lines(out0$res$t, out0$res$NPP, type='l', col="black")
  lines(out0b$res$t, out0b$res$NPP, type='l', col="black", lty=2)
  lines(out0c$res$t, out0c$res$NPP, type='l', col="black", lty=3)



  plot(out0$res$Wl[11:t_rotation], out1$res$Wl[1:(t_rotation-10)])
  abline(c(0,1))

  out0$res$Wl[out0$res$t == 10] # leaf biomass at 10 years
  out2 <- run_3PG(t_rotation = t_rotation, t_seedling_replant = 10, Wl_init = out0$res$Wl[out0$res$t == 10], thin = NULL, replant = 1)
  out3 <- run_3PG(t_rotation = t_rotation, t_seedling_replant = 0, Wl_init = out0$res$Wl[out0$res$t == 10], thin = NULL, replant = 0)

  ## This shows that the model can now be simply offset by t_seedling_replant
  plot(out0$res$Wl[11:t_rotation], out2$res$Wl[1:(t_rotation-10)])
  abline(c(0,1))

  plot(out0$res$NPP[11:t_rotation], out2$res$NPP[1:(t_rotation-10)])
  abline(c(0,1))

  plot(out2$res$t + 10, out2$res$Wl, col='red', type='l', xlim=c(0,60), ylim=c(0,1))
  lines(out1$res$t + 10, out1$res$Wl, col='blue', type='l')
  lines(out3$res$t, out1$res$Wl, col='green', type='l')
  lines(out0$res$t, out0$res$Wl)


  ## Demonstrating peatland restoration model concept:
  t_rotation <- 200
  out0 <- run_3PG(t_rotation = t_rotation,
                  t_seedling_replant = 0,
                  thin = NULL,
                  f_E = 0.3,
                  A0.5 = 80)

  age_at_felling <- 50
  restoration_time <- 10

  # out0$res <- out0$res %>%
  #   filter(t >= age_at_felling) %>%
  #   mutate(t = t - age_at_felling)

  out0$res$NPP_bog <- 0.2
  out0$res$NPP_bog[out0$res$t < age_at_felling] <- 0
  out0$res$NPP_bog[out0$res$t >= age_at_felling & out0$res$t < restoration_time + age_at_felling] <- -0.1
  out0$res$NPP_cum <- 0
  out0$res$NPP_cum[age_at_felling:nrow(out0$res)] <- cumsum(out0$res$NPP[age_at_felling:nrow(out0$res)])
  out0$res$NPP_bog_cum <- 0
  out0$res$NPP_bog_cum[age_at_felling:nrow(out0$res)] <- cumsum(out0$res$NPP_bog[age_at_felling:nrow(out0$res)])

  t_payback <- which(out0$res$NPP_cum - out0$res$NPP_bog_cum < 0)[1]


  p1 <- ggplot(out0$res, aes(x=t, y=NPP)) +
    geom_line(col="green") +
    geom_ribbon(aes(ymin = 0, ymax = NPP), alpha=0.2, fill="green") +
    geom_line(aes(y=NPP_bog), col="red") +
    geom_ribbon(aes(ymin = 0, ymax = NPP_bog), alpha=0.2, fill="red") +
    geom_vline(xintercept = age_at_felling, linetype=2) +
    geom_vline(xintercept = t_payback) +
    scale_x_continuous(limits=c(0, 1.1*t_payback)) +
    theme_bw()

  png("../peatland_restoration_LCA.png", width=10, height=8, units="cm", res=300)
  p1
  dev.off()
}
